export const english = {
    landing: {
        heroTitle: "We put people at the forefront of our innovation and solutions",
        heroSubtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",
        heroBtn: "Join our partnership program",
        heroCard1: "Our Company",
        heroCard2: "Products & Entities",
        heroCard3: "Press Room",
        section2Title: "Driving Innovation, Solving Global and Business Problems",
        section2Subtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",
        section2CardTitle1: "Media Technology For Rapid Growth",
        section2CardSubtitle1: "Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.",
        section2CardTitle2: "Global Connectivity, Local Impact",
        section2CardSubtitle2: "Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.",
        section2CardTitle3: "Innovation For Business  Unleashed",
        section2CardSubtitle3: "Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.",
        section2CardTitle4: "Media Technology For Rapid Growth",
        section2CardSubtitle4: "Vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.",
        
        section3Title: "Unleash your ideas to the world around you",
        section3Subtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",
        section3BtnTitle: "Get in touch with us",

        section4Title: "Your partnership with BOSS Global",
        section4Subtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",

        section5Title: "Entities",
        section5Subtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",
        section5Tab1: "Products",
        section5Tab2: "Entities",
        section5SubTab1: "Settla",
        section5SubTab2: "Supplr",
        section5Settla: "Settla",
        section5SettlaSub: "Fintech - Remittance",
        section5Supplr: "Supplr",
        section5SupplrSub: "Transports - Global Logistics",
        section5Smg: "SMG",
        section5SmgSub: "SellMedia Group",
        section5SmgSub2: "Media - Advertising, Media Tech",
        section5MoneyTrip: "MoneyTRIP",
        section5MoneyTripSub: "Banking - Fintech, Remittance",
        section5MoneyTripSub2: "Digital Banking, Global Remittance",
        section5Btn: "Explore Product",
        section5Btn2: "Learn More",
        section5SettlaAbout: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",
        section5SupplrAbout: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",
        section5SmgAbout: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",
        section5SmgAbout2: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",
        section5Clientele: "Clientele",
        section5MoneyTripAbout: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",
        section5MoneyTripAbout2: "Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time. Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.",

        section6Title: "Corporate Responsibilities",
        section6Subtitle: "From a small struggling businesses in a near village to an enterprise solution giants, we partner to make sense of your mission, vision and goals.",
        section6Card1: "Eco-Friendly environment initiative",
        section6Card2: "Tech education for communities",
        section6Card3: "Boss Global for business financial literacy",
    }
}